openapi: 3.0.1
info:
  title: Retsinfo-scraper
  version: 1.0.0
  description: GPT-handling til udtræk af gældende regler fra retsinformation.dk som XML. Bemærk: Anvender intern whitelist for at begrænse opslag til godkendte bekendtgørelser.
servers:
  - url: https://nyretsinfoxml.onrender.com
paths:
  /extract_text:
    post:
      summary: Hent og udtræk tekst fra XML-lovgivningsside
      operationId: extractText
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - url
              properties:
                url:
                  type: string
                  description: Retsinformation-URL til bekendtgørelse (med eller uden /xml)
      responses:
        '200':
          description: Udtrukket tekst
          content:
            application/json:
              schema:
                type: object
                properties:
                  tekst:
                    type: string

