openapi: "3.0.1"
info:
  title: Retsinfo-scraper
  version: "1.0.0"
  description: |
    Hent og udtræk tekst fra gældende bekendtgørelser på retsinformation.dk via XML-sider.
    API’et begrænser opslag til whitelisted bekendtgørelser.

servers:
  - url: https://nyretsinfoxml.onrender.com
    description: Produktion

paths:
  /extract_text:
    post:
      operationId: extractText
      summary: Udtræk tekst fra retsinformation.dk
      description: |
        Modtager en URL til en bekendtgørelse på retsinformation.dk og returnerer den udtrukne tekst.
        Kun whitelisted bekendtgørelser er tilladt.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: uri
                  description: Retsinformation-URL (f.eks. med eller uden /xml)
                  example: https://www.retsinformation.dk/eli/lta/2024/123
              required:
                - url
      responses:
        '200':
          description: Tekst udtrukket succesfuldt
          content:
            application/json:
              schema:
                type: object
                properties:
                  tekst:
                    type: string
                    description: Den udtrukne tekst fra bekendtgørelsen
                    example: "Denne bekendtgørelse fastsætter regler om..."
        '400':
          description: Ugyldig anmodning (fx ugyldig URL eller ikke whitelisted)
        '500':
          description: Intern serverfejl under behandlingen
