openapi: "3.1.0"
info:
  title: Retsinfo-scraper
  version: "1.0.0"
  description: >
    Udtræk tekst fra gældende bekendtgørelser på retsinformation.dk.
    Modtager en URL til en bekendtgørelse og returnerer dens tekstindhold.
    Kun whitelisted bekendtgørelser understøttes.

servers:
  - url: https://nyretsinfoxml.onrender.com

paths:
  /extract_text:
    post:
      operationId: extractText
      summary: Udtræk tekst fra retsinformation.dk bekendtgørelse
      description: |
        Returnerer bekendtgørelsestekst fra en XML-side på retsinformation.dk.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - url
              properties:
                url:
                  type: string
                  format: uri
                  description: URL til bekendtgørelsen (f.eks. med eller uden /xml)
                  examples:
                    - https://www.retsinformation.dk/eli/lta/2024/123
      responses:
        '200':
          description: Udtrukket tekst fra bekendtgørelsen
          content:
            application/json:
              schema:
                type: object
                properties:
                  tekst:
                    type: string
                    description: Udtrukket brødtekst
                    examples:
                      - "Denne bekendtgørelse fastsætter regler om..."
        '400':
          description: Ugyldig anmodning (fx forkert eller uwhitelisted URL)
        '500':
          description: Intern serverfejl under behandlingen

components: {}
