openapi: 3.1.0
info:
  title: Retsinfo-scraper (kun gældende XML)
  version: 1.2.0
  description: GPT-handlinger til at finde accessionsnumre via Google og kun returnere gældende dokumenter fra retsinformation.dk.
servers:
  - url: https://nyretsinfoxml.onrender.com
paths:
  /search_accession:
    post:
      operationId: searchAccession
      summary: Søg accessionsnummer via Google (kun gældende)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: Søgeord, fx 'køreprøve', 'syn', 'fartgrænser'
              required:
                - query
      responses:
        '200':
          description: Returnerer gældende accessionsnummer eller fejl
  /extract_text:
    post:
      operationId: extractText
      summary: Udtræk tekst fra XML-side på retsinformation.dk
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: Direkte URL til XML-siden for dokumentet
              required:
                - url
      responses:
        '200':
          description: Den udtrukne tekst fra XML-dokumentet
