openapi: "3.1.0"
info:
  title: Retsinfo-scraper
  version: "1.0.0"
  description: >
    Udtræk tekst fra gældende bekendtgørelser på retsinformation.dk.
    API’et returnerer brødteksten fra whitelisted bekendtgørelser baseret på en URL.

servers:
  - url: https://nyretsinfoxml.onrender.com

paths:
  /extract_text:
    post:
      operationId: extractText
      summary: Udtræk tekst fra retsinformation.dk bekendtgørelse
      description: Returnerer tekst fra XML-visning af en bekendtgørelse.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExtractTextRequest"
      responses:
        '200':
          description: Udtrukket tekst
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExtractTextResponse"
        '400':
          description: Ugyldig anmodning
        '500':
          description: Serverfejl

components:
  schemas:
    ExtractTextRequest:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          format: uri
          description: URL til bekendtgørelsen (f.eks. med eller uden /xml)
          examples:
            - https://www.retsinformation.dk/eli/lta/2024/123

    ExtractTextResponse:
      type: object
      properties:
        tekst:
          type: string
          description: Udtrukket brødtekst fra bekendtgørelsen
          examples:
            - "Denne bekendtgørelse fastsætter regler om..."
