openapi: 3.1.0
info:
  title: Retsinfo-scraper
  version: 1.0.0
  description: GPT-handlinger til at søge og læse bekendtgørelser og love fra retsinformation.dk
servers:
  - url: https://nyretsinfoxml.onrender.com
    description: Live API på Render
paths:
  /search_laws:
    post:
      operationId: searchLaws
      summary: Søg på retsinformation.dk
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: Hvad skal der søges efter, fx navneloven, køreuddannelse, syn
              required:
                - query
      responses:
        '200':
          description: Links og titler fra retsinformation.dk
  /extract_text:
    post:
      operationId: extractText
      summary: Udtræk tekst fra XML-side på retsinformation.dk
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: Direkte URL til XML-siden for dokumentet på retsinformation.dk
              required:
                - url
      responses:
        '200':
          description: Den udtrukne tekst fra XML-dokumentet
