openapi: "3.1.0"
info:
  title: Retsinfo-scraper
  version: "1.0.0"
  description: |
    Udtræk tekst fra gældende bekendtgørelser på retsinformation.dk.
    Modtag en URL til en bekendtgørelse og returnér dens indhold som tekst.
    Kun whitelisted bekendtgørelser kan behandles.

servers:
  - url: https://nyretsinfoxml.onrender.com
    description: Produktion

paths:
  /extract_text:
    post:
      operationId: extractText
      summary: Udtræk tekst fra retsinformation.dk
      description: |
        Henter og udtrækker tekst fra en XML-side for en bekendtgørelse på retsinformation.dk.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: uri
                  description: URL til bekendtgørelsen (med eller uden /xml)
                  examples:
                    eksempel:
                      value: https://www.retsinformation.dk/eli/lta/2024/123
              required:
                - url
      responses:
        '200':
          description: Udtrukket tekst
          content:
            application/json:
              schema:
                type: object
                properties:
                  tekst:
                    type: string
                    description: Udtrukket tekst fra bekendtgørelsen
                    examples:
                      eksempel:
                        value: >
                          "Denne bekendtgørelse fastsætter regler om..."
        '400':
          description: Ugyldig anmodning – fx ugyldig eller ikke-whitelisted URL
        '500':
          description: Intern serverfejl

components: {}
